global:
  proxy:
    no_proxy: ""
    http_proxy: ""
    https_proxy: ""


name: vssui
image:
  repository: intel/vss-ui
  tag: "latest"
  pullPolicy: IfNotPresent
  resources: {}

containerPortName: vssui-port  # Optional name to refer containerPort
service:
  type: ClusterIP
  port: 80  # Port on which service listens for incoming connection

pipelineManagerEndpoint: "/manager"
assetsEndpoint: "/minio"

feature:
  summary: ""
  search: ""
  mux: ""
